services:
  prometheus:
    image: reg.undercloud.cri.epita.fr/docker/prom/prometheus:latest
    container_name: prometheus
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - /tmp/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - metrics-net

  grafana:
    image: reg.undercloud.cri.epita.fr/docker/grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - metrics-net
    depends_on:
      - prometheus

networks:
  metrics-net:
    external: true